apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
  namespace: llkhe
  labels:
    app: ms-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-a
  template:
    metadata:
      labels:
        app: ms-a
    spec:
      containers:
      - name: ms-a
        image: ms-a:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: REDIS_HOST
          value: "redis-0.redis"
        - name: REDIS_PORT
          value: "6379"

        readinessProbe:
          tcpSocket:
            port: 8181
          initialDelaySeconds: 40
          periodSeconds: 10

        livenessProbe:
          tcpSocket:
            port: 8181
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ms-a
  namespace: llkhe
spec:
  selector:
    app: ms-a
  ports:
  - port: 8181
    targetPort: 8181
    nodePort: 30181
  type: NodePort

